services:
  service:
    image: ghcr.io/foundry-rs/foundry:latest
    ports:
      - 8545:8545
      - 8546:8546
    volumes:
      - ./:/app
  backend:
    image: ghcr.io/oasisprotocol/sapphire-localnet
    expose:
      - 8545
      - 8546
    command: -test-mnemonic
